# Generated by Django 4.0 on 2021-12-24 05:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Mailing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customer', models.CharField(max_length=100)),
                ('mailing_name', models.CharField(max_length=50)),
                ('mailing_dropoff_date', models.DateField()),
                ('mailing_type_description', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Mailpiece',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pieceId', models.UUIDField(editable=False, unique=True)),
                ('edocMailingGroupId', models.CharField(max_length=50)),
                ('idTag', models.CharField(max_length=50)),
                ('imb', models.CharField(max_length=31)),
                ('mailClassDescription', models.CharField(max_length=50)),
                ('imbMid', models.CharField(max_length=9)),
                ('imbRoutingCode', models.CharField(max_length=11)),
                ('imbTrackingCode', models.CharField(max_length=20)),
                ('expectedDeliveryDate', models.DateField()),
                ('startTheClockDate', models.DateField()),
                ('imbSerialNumber', models.CharField(max_length=11)),
                ('imbStid', models.CharField(max_length=3)),
                ('anticipatedDeliveryDate', models.DateField()),
                ('predictedDeliveryDate', models.DateField()),
                ('routingCodeImbMatchingPortion', models.CharField(max_length=11)),
                ('edocSubmitterCrid', models.CharField(max_length=15)),
                ('edocJobId', models.CharField(max_length=50)),
                ('recipient', models.CharField(max_length=50)),
                ('title', models.CharField(max_length=50)),
                ('company', models.CharField(max_length=50)),
                ('address1', models.CharField(max_length=150)),
                ('address2', models.CharField(max_length=150)),
                ('address3', models.CharField(max_length=150)),
                ('city', models.CharField(max_length=150)),
                ('state', models.CharField(max_length=2)),
                ('zip', models.CharField(max_length=9)),
                ('mailing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.mailing')),
            ],
        ),
        migrations.CreateModel(
            name='Scan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanLocaleKey', models.CharField(max_length=10)),
                ('machineName', models.CharField(max_length=10)),
                ('scanFacilityCity', models.CharField(max_length=100)),
                ('scanFacilityState', models.CharField(max_length=2)),
                ('scannerType', models.CharField(max_length=50)),
                ('scanDatetime', models.DateTimeField()),
                ('handlingEventTypeDescription', models.CharField(max_length=25)),
                ('scanFacilityZip', models.CharField(max_length=9)),
                ('machineId', models.CharField(max_length=10)),
                ('handlingEventType', models.CharField(max_length=10)),
                ('scanFacilityName', models.CharField(max_length=50)),
                ('piece_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.mailpiece')),
            ],
        ),
    ]
