# Generated by Django 4.0 on 2021-12-28 20:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0002_mailpiece_first_seen'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailing',
            name='job_number',
            field=models.CharField(default=0, max_length=15),
            preserve_default=False,
        ),
    ]
