# Generated by Django 4.0 on 2021-12-30 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0003_mailing_job_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailpiece',
            old_name='address3',
            new_name='address_extra',
        ),
        migrations.RemoveField(
            model_name='mailpiece',
            name='first_seen',
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='bundle_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='container_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='imb_alpha',
            field=models.CharField(default=0, max_length=75),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='imb_numeric',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='manifest_key',
            field=models.CharField(default=0, max_length=25),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='oel',
            field=models.CharField(default=0, max_length=50),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='record_number',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='mailpiece',
            name='sort_order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
