# Generated by Django 4.0 on 2022-01-03 02:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0004_rename_address3_mailpiece_address_extra_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='imb_numeric',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.AddIndex(
            model_name='mailpiece',
            index=models.Index(fields=['imb_numeric'], name='Tracker_mai_imb_num_e31d6f_idx'),
        ),
    ]
