# Generated by Django 4.0 on 2022-01-03 03:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0005_alter_mailpiece_imb_numeric_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='pieceId',
            field=models.UUIDField(editable=False),
        ),
    ]
