# Generated by Django 4.0 on 2022-01-03 03:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0006_alter_mailpiece_pieceid'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailpiece',
            old_name='pieceId',
            new_name='pieceIdUUID',
        ),
    ]
