# Generated by Django 4.0 on 2022-01-03 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0008_alter_mailpiece_pieceiduuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='anticipatedDeliveryDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='expectedDeliveryDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='pieceIdUUID',
            field=models.UUIDField(blank=True, editable=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='predictedDeliveryDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='record_number',
            field=models.IntegerField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='startTheClockDate',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='state',
            field=models.CharField(blank=True, max_length=2),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='zip',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
