# Generated by Django 4.0 on 2022-01-03 03:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0010_alter_mailpiece_pieceiduuid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='anticipatedDeliveryDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='expectedDeliveryDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='predictedDeliveryDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='record_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='startTheClockDate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='state',
            field=models.CharField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='zip',
            field=models.CharField(max_length=9, null=True),
        ),
    ]
