# Generated by Django 4.0 on 2022-01-03 03:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0012_alter_mailpiece_bundle_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='container_number',
            field=models.IntegerField(null=True),
        ),
    ]
