# Generated by Django 4.0 on 2022-01-03 03:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0013_alter_mailpiece_container_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='sort_order',
            field=models.IntegerField(null=True),
        ),
    ]
