# Generated by Django 4.0 on 2022-01-03 06:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0014_alter_mailpiece_sort_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mailing_list', models.FileField(upload_to='cars')),
            ],
        ),
        migrations.RemoveIndex(
            model_name='mailpiece',
            name='Tracker_mai_imb_num_e31d6f_idx',
        ),
        migrations.RemoveField(
            model_name='mailpiece',
            name='imb_alpha',
        ),
        migrations.RemoveField(
            model_name='mailpiece',
            name='imb_numeric',
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='imb',
            field=models.CharField(max_length=31, unique=True),
        ),
        migrations.AddIndex(
            model_name='mailpiece',
            index=models.Index(fields=['imb'], name='Tracker_mai_imb_a74f5d_idx'),
        ),
        migrations.AddField(
            model_name='files',
            name='mailing_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Tracker.mailing'),
        ),
    ]
