# Generated by Django 4.0 on 2022-01-03 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0015_files_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='zip',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
