# Generated by Django 4.0 on 2022-01-03 09:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0017_alter_mailing_mailing_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mailpiece',
            old_name='pieceIdUUID',
            new_name='pieceId',
        ),
    ]
