# Generated by Django 4.0 on 2022-01-03 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Tracker', '0018_rename_pieceiduuid_mailpiece_pieceid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mailpiece',
            name='address1',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='address2',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='address_extra',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='city',
            field=models.CharField(max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='company',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='edocJobId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='edocMailingGroupId',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='edocSubmitterCrid',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='idTag',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='imbMid',
            field=models.CharField(max_length=9, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='imbRoutingCode',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='imbStid',
            field=models.CharField(max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='imbTrackingCode',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='manifest_key',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='oel',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='recipient',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='routingCodeImbMatchingPortion',
            field=models.CharField(max_length=11, null=True),
        ),
        migrations.AlterField(
            model_name='mailpiece',
            name='title',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
